/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf --transform 
Files: scene.gltf [124.12KB] > C:\Users\noyal\OneDrive - Liverpool Hope University\Uni Year 3\Dissertation\Dissertation_Implementation\adhd\src\assets\cozy_lake\scene-transformed.glb [34.43KB] (72%)
Author: Christian Lüdeking (https://sketchfab.com/happitack)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cozy-lake-55d48e0250384ed9811c1567fd3fa7fd
Title: Cozy Lake
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import scenePath from './scene-transformed.glb'
export function Model(props) {
  const { nodes, materials } = useGLTF(scenePath);
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Island_01_Water_0.geometry} material={materials.PaletteMaterial001} position={[31.111, -70.209, 9.981]} rotation={[-Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Tree_Dense_01_Wood_0.geometry, materials.PaletteMaterial001, 5]} instanceMatrix={nodes.Tree_Dense_01_Wood_0.instanceMatrix} />
      <instancedMesh args={[nodes['Mushroom_05_Material_#26_0'].geometry, materials.PaletteMaterial001, 5]} instanceMatrix={nodes['Mushroom_05_Material_#26_0'].instanceMatrix} />
      <instancedMesh args={[nodes.Mushroom_05_Metal_0.geometry, materials.PaletteMaterial001, 5]} instanceMatrix={nodes.Mushroom_05_Metal_0.instanceMatrix} />
      <instancedMesh args={[nodes.Mushroom_05_Rock_0.geometry, materials.PaletteMaterial001, 5]} instanceMatrix={nodes.Mushroom_05_Rock_0.instanceMatrix} />
    </group>
  )
}

useGLTF.preload(scenePath)
